const productTypes = {
  RESET_ALL_VALUES: 'RESET_ALL_VALUES',
  CLEAN_ERRORS: 'CLEAN_ERRORS',
  CREATE_AD_SUCCESS: 'CREATE_AD_SUCCESS',
  CREATE_AD_ERROR: 'CREATE_AD_ERROR',
  CHECK_STOCK_SUCCESS: 'CHECK_STOCK_SUCCESS',
  CHECK_STOCK_ERROR: 'CHECK_STOCK_ERROR',
};

export default productTypes;
